server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/message_db?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
    username: mysqluser
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
